### ISSUE TITLE
Remote Feature Finish

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#110]
Noting Raam's comments here in a private/internal discussion we had:
https://websharks.slack.com/archives/phings/p1464993216000002

**Comment by raamdev** [comment]
Copying the comments from Slack to here:

---

@raamdev writes...

Regarding `phing feature-finish` (https://github.com/websharks/phings/wiki/GitHub-Features):

I used this just now and got the following error:

> The feature/728 branch still exists at remote origin. It must be merged & deleted by the project lead first.

Hmm, I normally do this with the Hubflow tools using `git hf feature finish -f`, with the `-f` flag indicating to Hubflow that I want to "force merge of feature branch if not merged yet at origin". This allows me to merge a PR from my local command line instead of using the GitHub merge button on the PR (which I can't do because my personal email ends up in the commit instead of my WebSharks email address).

Is there any way to accomplish this with Phing as it stands now, or would that require modifications?

---

@jaswsinc writes...

Cool. That sounds like a nice addition to the `websharks/phing` project. As it stands right now that functionality is more or less a copy of what my personal bash script was doing, but I'm happy to add this in.

So you want `phing feature-finish -D force=true` to do a `git merge --no-ff feature/123` and then push those changes to the remote. Do I have that right?

---

@raamdev writes...

I think so, yes. Here's the area of Hubflow related to this: 
https://github.com/websharks/hubflow/blob/000000-dev/git-hf-feature#L341

See also `hubflow_push_latest_changes_to_origin()`: https://github.com/websharks/hubflow/blob/000000-dev/hubflow-common#L401

**Comment by jaswrks** [comment]
_Noting that not all feature branches should be targeted at the `dev` branch. Some feature branches are intended to be merged into; e.g., an existing RC release branch._

**Comment by jaswrks** [comment]
@raamdev This has been implemented. You can now run through the full merge/push/delete/finish cycle locally — bypassing the PR on GitHub if you'd like. I documented the workflow [here](https://github.com/websharks/phings/wiki/GitHub-Features#finishing-a-github-issue-forced-merge-alternative).

**Comment by raamdev** [comment]
@jaswsinc This new feature is not behaving the way I expected.

@raamdev writes...
>  I normally do this with the Hubflow tools using `git hf feature finish -f`, with the `-f` flag indicating to Hubflow that I want to "force merge of feature branch if not merged yet at origin". This allows me to merge a PR from my local command line instead of using the GitHub merge button on the PR (which I can't do because my personal email ends up in the commit instead of my WebSharks email address).

The goal here is to be able to "force merge of feature branch if not merged yet at origin". If there's a PR currently open and I, as the project lead, am ready to merge that PR, I should be able to do that from the command line (i.e., I shouldn't need to merge the PR on GitHub, or delete the branch on GitHub).

In HubFlow, I accomplish this via `git hf feature finish -f`. I expected `phing feature-finish -D force=true` to accomplish the same thing, but it doesn't:


```
$ phing feature-finish -D force=true
[...]
PHP PSR-4 Project > -features-feature:

     [echo] Currently on a dev or feature branch. OK.
     [echo]
     [echo] Fetching latest copy of all branches from remote origin.
[phingcall] /Users/raam/Projects/sandbox/phings/src/psr4/targets/features/feature.xml:91:8: /Users/raam/Projects/sandbox/phings/src/psr4/targets/features/feature.xml:97:12: /Users/raam/Projects/sandbox/phings/src/psr4/targets/features/feature.xml:102:154: The feature/9 branch still exists at remote origin. It must be merged & deleted by the project lead first.

BUILD FAILED
/Users/raam/Projects/sandbox/phings/src/psr4/targets.xml:223:43: Execution of the target buildfile failed. Aborting.
Total time: 4.2229 seconds
```

**Comment by jaswrks** [comment]
Hmm, I can't seem to reproduce this. I was able to do exactly what you described and I did not get that error. I see that was with the websharks/sandbox repo? Try updating that repo to the latest phings.

**Comment by raamdev** [comment]
> Try updating that repo to the latest phings.

I updated to the latest version of Phings before running my tests; see https://github.com/websharks/sandbox/commit/2ffd5664c7db94bb6d747199c7065ffbc91231c0.
