### ISSUE TITLE
Version Bump in All Targets?

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#111]
@raamdev writes...

> Well, it doesn't need to change in PRs... I was thinking the version number would only change in the distributable zip that gets generated (which we all use for building an installable version of our branch for testing purposes). The local working copy wouldn't have the version number changed, since that only needs to happen during a release when the bumped version number needs to be committed.

**Comment by jaswrks** [comment]
I see. That sounds like it could work well then.

So we just need to get a version replacement routine into the build directory phase and have it run at all times instead of conditionally like the other one does. Do I have that right?

**Comment by raamdev** [comment]
> So we just need to get a version replacement routine into the build directory phase and have it run at all times instead of conditionally like the other one does. Do I have that right?

Yes, that sounds perfect. For everything except the `release` and `release-rc`, the version format could be something like `v160606.80279`, so that a developer running a build multiple times during the day and re-testing would see a different version number each time (as opposed to the same version number all day).

**Comment by jaswrks** [comment]
Next Release Changelog:
- Adding `${_project_build_version}` in build directory phase. See: #111
