### ISSUE TITLE
Add support for @deprecated to @since xxxxxx replacement

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#130]
The Phing replacement of `@since 16xxxx` worked well during the latest Comet Cache release, but there was an edge case that it missed:
- https://github.com/websharks/comet-cache-pro/blob/160629-RC/src/includes/traits/Shared/ReplaceUtils.php#L11
- https://github.com/websharks/comet-cache-pro/blob/160629-RC/src/includes/traits/Shared/ReplaceUtils.php#L40

**Comment by raamdev** [comment]
@jaswsinc <del>Any idea why it missed these lines?</del> Sorry, I just realized these are `@deprecated` lines — 😴

**Comment by jaswrks** [comment]
The `@deprecated` tag is now supported. However, please note the following:
- You must type it out where the version comes immediately after the `@deprecated` tag.

## Examples

``` php
/**
 * @deprecated 16xxxx Whatever note you want to leave.
 * @deprecated xxxxxx This works too; i.e., with no numbers.
 * @since 16xxxxxxxx This works too; i.e., 2 numbers followed by 4 or more x's.
 * @since xxxxxxxxxx This works too; i.e., 6 or more x's.
 */
```

## Suggested Alternative

The Phing build system also supports `$v` as a replacement code, and since that is shorter and easier to recognize as something that is going to be replaced automatically, that is what I suggest.

``` php
/**
 * @since      $v Whatever note you want to leave.
 * @deprecated $v Whatever note you want to leave.
 */
```
