### ISSUE TITLE
Release notifications should go to project-specific Slack channel

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#132]
![2016-08-05_11-17-49](https://cloud.githubusercontent.com/assets/53005/17441266/4213a2b2-5afe-11e6-96bf-1c0015598e84.png)

@raamdev writes...

> Can we put those automated bleeding edge notifications in a separate channel? The project-specific channel would make more sense than the global #company channel.

@jaswsinc writes...

> Agree. I think the official release announcements should be in a project-specific channel also. This will need to be updated in the build system by one of us.

**Comment by jaswrks** [comment]
Next Release Changelog:
- Slack notification channel. See: #132

**Comment by jaswrks** [comment]
Reopening this issue. The Slack channel needs to be configurable, for two reasons.
1. Slack has a limit on the number of characters allowed in a channel. If the project slug exceeds that limit, we will be forced to get creative with the Slack channel name, and therefore the automatic mapping will be thrown off in that case; e.g., `woocommerce-kb-articles` is too long.
2. Some projects may _prefer_ to ride on a parent project channel for notifications. Or, they might prefer to use a shorter channel name for easier Slack navigation; e.g., `wc-intercom` instead of `woocommerce-intercom`.
