### ISSUE TITLE
Remove POT Generation for Lite Version

### ISSUE THREAD

**Issue by jaswrks** [websharks/phings#51]
A fork of #50...

@jaswsinc writes...

> what we probably do need to change, is the way the POT is generated in our Phing build for the lite variation. At present, the lite POT is generating separately from the pro version, which cuts away any pro-only strings from the POT we ship in the lite version. I think that shouldn't be the case. The POT for both should be the same, just like the text domain.

**Comment by raamdev** [comment]
> The POT for both should be the same, just like the text domain.

Umm, no. Because the POT file includes line numbers for where the translated strings appear. Since the Lite version is the Pro version with a lot of code stripped out, the line numbers won't match up. I.e., you need to have two separate POT files.

**Comment by jaswrks** [comment]
How important are the line numbers whenever you build a translation? My understanding was that this was simply extra metadata there for easy reference, not necessarily something vital to the translator.

**Comment by jaswrks** [comment]
Well. I agree that in either case it is less than ideal. Line numbers being wrong is not cool. Hmm.

**Comment by jaswrks** [comment]
I guess we can just leave it as-is then, but then we will, as you said, need to split this into two different text domains in that case. That's unfortunate, because it will fragment translations. I don't see any way around that though. Do you?

Referencing: https://github.com/websharks/phings/pull/50#issuecomment-190913668

**Comment by raamdev** [comment]
I did some research. Line numbers in the POT file are indeed just comments but they are specifically designed to help translators find where in the source code the message has been extracted from, so that if the translator needs more context while translating, they can easily look up where in the source code the message is used.

Programs such as Poedit make it easy for translators to look up usages in the source code (assuming those line numbers are correct):

![2016-03-03_07-56-11](https://cloud.githubusercontent.com/assets/53005/13494976/c2134e8a-e115-11e5-92a2-32975da27068.png)

So, if we just included the Pro POT file with the Lite version, these would be the downsides:
- Makes it harder to translate the Lite version because the POT will be larger than necessary and contain _many_ strings that are not found in the Lite version.
- Makes it harder to translate the Lite version because the POT will contain strings and references that make no sense in the context of the Lite features.
- Makes it harder to translate the Lite version because line numbers referencing messages used in the source code will be wrong. 

![2016-03-03_08-10-57](https://cloud.githubusercontent.com/assets/53005/13495232/81a9b27e-e117-11e5-8924-06422ae54daa.png)

---

## But all of this is a moot point, IMO.

I was starting to make an argument for continuing to regenerate the POT file for the Lite version, but then I remembered what I read in [the translate.wordpress.org announcement](https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/): 

> **What if my plugin already ships translations?**
> 
> Translations that are already shipped in plugins will be initially imported into translate.wordpress.org. Again: we’ll import the strings and the translations on the initial import. We won’t continue to do that because **the end goal would be for plugin authors to remove the translations from their download, allowing language packs to fill the void.** (emphasis added)

The whole goal of translate.wordpress.org is to allow all translations (for Core, Themes, and Plugins) to occur over there, in a centralized place. When you enable a specific language in WordPress, translate.wordpress.org will automatically be searched for a matching language pack for each theme/plugin installed on your WordPress site. It's a central translation repository for WordPress. Simply put: awesome and amazing for translations.

Since the Lite version of our software is intended for the WordPress.org plugin repo, I'd say we should just exclude the POT file from the Lite version altogether, i.e., exclude the whole `translations/` directory. If Lite users ask about a default POT file, we should point them to translate.wordpress.org and ask them to submit their translation over there.

**Comment by jaswrks** [comment]
Cool. Thanks for doing that research. So we can stop generating the POT for the lite version altogether, and it sounds like we do need to use a separate text-domain for the pro version, and that we need to generate a POT for the pro version.

**Comment by raamdev** [comment]
> we can stop generating the POT for the lite version altogether

Yes.

> it sounds like we do need to use a separate text-domain for the pro version

That probably makes sense, yes. But since the Lite and Pro versions can't be running at the same time, I don't think it matters. The only scenario where I see there being a problem with the text domain the same is if both plugins were listed on something like translate.wordpress.org, where the text-domain is required to be unique to have two listings... but that doesn't seem like a likely scenario to me.

So, I'm fine keeping a single text domain.

> we need to generate a POT for the pro version.

Correct.

**Comment by jaswrks** [comment]
This will be corrected by: https://github.com/websharks/phings/pull/83

**Comment by jaswrks** [comment]
Resolved by https://github.com/websharks/phings/releases/tag/160416
