### ISSUE TITLE
PHP Warnings, Strict Standards, and Deprecated messages related to wp-i18n-tools/160416.phar

### ISSUE THREAD

**Issue by raamdev** [websharks/phings#89]
While building the `000000-dev` branch of both Comment Mail Pro and Comet Cache Pro (as of 2016-04-21) using Phings v160418 and running the command `phing full-build-all`, I'm getting lots of the following notices:

```
[...]
PHP Strict Standards:  Only variables should be passed by reference in phar:///Users/raam/.websharks/phings/deps/wp-i18n-tools/160416.phar/extract/extract.php on line 22
PHP Strict Standards:  Only variables should be passed by reference in phar:///Users/raam/.websharks/phings/deps/wp-i18n-tools/160416.phar/extract/extract.php on line 25
PHP Strict Standards:  Only variables should be passed by reference in phar:///Users/raam/.websharks/phings/deps/wp-i18n-tools/160416.phar/extract/extract.php on line 25
PHP Strict Standards:  Only variables should be passed by reference in phar:///Users/raam/.websharks/phings/deps/wp-i18n-tools/160416.phar/extract/extract.php on line 22
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in phar:///Users/raam/.websharks/phings/deps/wp-i18n-tools/160416.phar/makepot.php on line 187
PHP Deprecated:  Non-static method MakePOT::get_first_lines() should not be called statically, assuming $this from incompatible context in phar:///Users/raam/.websharks/phings/deps/wp-i18n-tools/160416.phar/pot-ext-meta.php on line 35
PHP Deprecated:  Non-static method MakePOT::get_addon_header() should not be called statically, assuming $this from incompatible context in phar:///Users/raam/.websharks/phings/deps/wp-i18n-tools/160416.phar/pot-ext-meta.php on line 38
PHP Deprecated:  Non-static method MakePOT::get_addon_header() should not be called statically, assuming $this from incompatible context in phar:///Users/raam/.websharks/phings/deps/wp-i18n-tools/160416.phar/pot-ext-meta.php on line 38
PHP Deprecated:  Non-static method MakePOT::get_addon_header() should not be called statically, assuming $this from incompatible context in phar:///Users/raam/.websharks/phings/deps/wp-i18n-tools/160416.phar/pot-ext-meta.php on line 38
[...]
```

```
$ php --version
PHP 5.6.20 (cli) (built: Apr 18 2016 11:28:21)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by jaswrks** [comment]
Thanks for the report and that output.

> PHP Warning:  date():

This one you should be able to get rid of by updating your `php.ini` file. It's a common issue whenever the default ini file is in use and you will see that error in any script that displays errors until it is resolved. See: http://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings

I suggest: `date.timezone = UTC`

---

The rest of those seem to be in the i18n tools package, which is a fork of the WordPress i18n tools with slight modifications. I'm going to open a separate issue for this in the i18n repo [here](https://github.com/websharks/wp-i18n-tools/issues/4).

However, the errors you're seeing there would indicate that error reporting is at a debug level. So you might want to [add this](https://github.com/websharks/ubuntu-bootstrap/blob/master/src/php/.ini#L24) to your `php.ini` file also, because you're using PHP as a utility in this case, not just for local development; i.e., you don't want your own tools (those that rely on PHP) to choke on debug-level notices. See: https://github.com/websharks/ubuntu-bootstrap/blob/master/src/php/.ini#L24

**Comment by raamdev** [comment]
> I suggest: date.timezone = UTC

That fixed it. Thanks! 

> you're using PHP as a utility in this case, not just for local development; i.e., you don't want your own tools (those that rely on PHP) to choke on debug-level notices. See: https://github.com/websharks/ubuntu-bootstrap/blob/master/src/php/.ini#L24

Right. That makes sense. Fixed. Thanks!
